### ISSUE TITLE
TE: wall subdivisions disappear

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#763] opened 2024-01-10 19:44 UTC
I tried the new features (more than five [2 upper, 1 middle, 2 lower] wall subdivisons), and I experienced this:
Using 1-9 number keys I can have even 9 upper, 1 middle, 9 lower subdivisions. Which means maximum 9 subdivisions on floor sector side walls, and maximum 9 subdivisions on ceiling sector side walls.
So I also tried these 9-9 subdivisions even on special side walls: the yellow ones, which are at portals.
I could do it successfully.
But:
The problem is: the PRJ2 won't save extra amount of subdivisions on the yellow walls.
Loading PRJ2 after that, yellow walls will be loaded with one subdivision on each.

Additional issues to these new features (probably only when I try some complex movement with the lines between the subdivisions - eg. one of the two selected panels is a normal wall panel, the other one is a yellow one; or using a preset Tool Panel special forming function on more than one selected panels):
- Sometimes undo/redo seems frozen after doing this (buttons remains active, though).
- The black lines between subdivisons sometimes become blurred, pale after some action like this. I suspect it means something is not okay (as if there were overlapping parts). (No, I'm not saying the lines are white, I know those are white when I hit the key - it is okay.)

EDIT:
And I could say more than this to this issue, tyring more things:
- deleting the portal here, that also removes the lines,
- white marks are not always shown on yellow walls, when I hit the the key to their lines

EDIT2:
First use subdivisons on walls, only then open the portal. That seems worse, the other one (first portal, then subdivisions) seems having less issues (?).

**Comment by AkyV** [comment] 2024-01-10 19:52
EDIT:
And I could say more than this to this issue, tyring more things:
- deleting the portal here, that also removes the lines,
- white marks  are not always shown on yellow walls, when I hit the the key to their lines

**Comment by Nickelony** [comment] 2024-01-13 07:17
The undo / redo issue is already known and it doesn't just affect the subdivisions, but every geometry action in general.
I noticed on shabaobab's Stream that textures sometimes don't save correctly on yellow walls. Seems like portals are very messed up.

**Comment by AkyV** [comment] 2024-01-13 10:05
Hello!
See "TE: Bad direction to open portals #691" issue.
Perhaps that is also related.

**Comment by Nickelony** [comment] 2024-01-13 10:27
> Sometimes undo/redo seems frozen after doing this (buttons remains active, though).

**That has just been fixed.**

> deleting the portal here, that also removes the lines,

**This is intended behavior, since the yellow block belongs to the other room. Removing the portal restores the block from the current room, which is the one that was there before the portal was created.**

> The black lines between subdivisons sometimes become blurred, pale after some action like this.

This is super weird... I have never seen this, nor can I reproduce this.

> white marks are not always shown on yellow walls, when I hit the the key to their lines

I have noticed that, but I'm not sure what's causing it. I will investigate this.

**Comment by Nickelony** [comment] 2024-01-13 10:33
@AkyV
> Loading PRJ2 after that, yellow walls will be loaded with one subdivision on each.

Can you please send me an example of how to replicate this, I can't get it on my side, no matter what I do.

**Comment by AkyV** [comment] 2024-01-13 12:42
deleting the portal here, that also removes the lines,

This is intended behavior, since the yellow block belongs to the other room. Removing the portal restores the block from the current room, which is the one that was there before the portal was created.
-------------

Generally true, but see this example:

1. Subdivisions are made:
![image](https://github.com/MontyTRC89/Tomb-Editor/assets/34724172/bd5b418a-9674-4484-806a-2095b61817da)

2. Portal is opened - subdivisons are kept from this room:

![image](https://github.com/MontyTRC89/Tomb-Editor/assets/34724172/4c6ea0a7-43dc-4e22-ae10-ab86f00d4904)

3. Portal is deleted - subdivisions, made in this room, are restored:
Strange, previously they are gone for me...

However, Item#2 is still unusual, isn't it?

I also answer the other ones, give me some minutes. :)

**Comment by AkyV** [comment] 2024-01-13 13:02
The black lines between subdivisons sometimes become blurred, pale after some action like this.

This is super weird... I have never seen this, nor can I reproduce this.

----------------------------------
Try what I did in the previous images just above, then try to move each line in the upper part, where some subdivisons seemingly cannot be there (i.e. less than 9). I mean try 1, 2, 3 etc., all. - And you'll see: there will be blurred lines, on some panel lines will be all gone with a movement like this!

**Comment by AkyV** [comment] 2024-01-13 13:03
The black lines between subdivisons sometimes become blurred, pale after some action like this.

This is super weird... I have never seen this, nor can I reproduce this.

------------------------

Reproduce again what I posted on images above (except deleting the portal), save/load: and the lines are all gone!

**Comment by Nickelony** [comment] 2024-01-13 20:56
All right, so I found out when exactly the subdivisions disappear...
This only happens when you manually connect two rooms, without using portal digger.
For some reason, the geometry from room 1 doesn't get transferred over to room 2.
I am looking into this deeper, but this seems like an original TE bug yet again.

**Comment by Nickelony** [comment] 2024-01-13 21:43
Source of issue seems to be `RoomGeometry.cs`, because when I turn on Legacy Geometry Code, it seems to act normally.

**Comment by Nickelony** [comment] 2024-01-13 22:04
All issues seem to be 🦊 now. Removing all subdivisions of blocks where a portal was created seemed to do the trick.
This includes:
- Undo / Redo now works on yellow walls.
- White marks now always show correctly.
- Creating a portal manually won't leave phantom subdivisions, which shouldn't be there anymore.
- Fixing the issue above eliminates the issue where reloading the prj2 would show different geometry than before.

**Closed by Nickelony** 2024-01-13 22:04 UTC
Labels: bug, high priority
