### ISSUE TITLE
Changing sound ID in SoundTool without deleting sound info

### ISSUE THREAD

**Issue by WalrusTR** [MontyTRC89/Tomb-Editor#534] opened 2022-02-08 15:38 UTC
Sound ID window doesn't allow to change the ID of an existing sound without deleting the sound info. It is possible copy sound info, deleting the existing one, add the new sound info with different ID and paste the info there, but just changing sound ID would be better and faster. A new button could be implemented on the bottom of the viewport below sounds list, similar to WadTool button to change object slot, but to change sound ID, with an optional warning message if the new slot is already taken and that will be replaced.

**Comment by Lwmte** [comment] 2022-02-09 12:11
Duplicate of #462

**Closed by Lwmte** 2022-02-09 12:11 UTC
Labels: enhancement, new feature, low priority
