### ISSUE TITLE
WT - Missing playback

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor#780] opened 2024-02-25 12:08 UTC
In AE:

At very short animations (like. eg. TR4 LARA's (4) WALK_TO_RUN_RIGHT or (5) WALK_TO_RUN_LEFT) the playback isn't present in the big middle window - though:

- I have started playback, "Playback" button shows a "square" now.
- Frame value at the bottom keeps changing. (Keyframe value remains constant 0.)
- If I click on another animation now, that starts animating nicely.

Chain playback naturally isn't set now.

**Comment by Lwmte** [comment] 2024-02-26 02:36
Your animations have end frame set to 1, which means, given that they contain only 2 keyframes and interpolation set to either 2 or 4, that ACTUAL played animation will never reach keyframe 2.

Therefore, it is not a bug of WT, but a bug of original assets. This bug was fixed in TEN base wad but still exists in legacy (e.g. tomb4) wads.

**Closed by Lwmte** 2024-02-26 02:36 UTC
