### ISSUE TITLE
WT: "Convert wad to TombEngine..." doesn't remap holsters

### ISSUE THREAD

**Issue by Joey79100** [MontyTRC89/Tomb-Editor#695] opened 2023-05-02 17:13 UTC
WadTool has a "Convert wad to TombEngine..." feature in the Tools menu.
You open the WAD you want to convert, open the Tools menu, hit "Convert wad to TombEngine...": it prompts you to type the name of the new WAD, and you click OK.

TombEditor also has its equivalent, which is "Convert level to TombEngine..." in the File menu.
This one does the necessary operations, which include converting each WAD.

When you use either of these features, in theory 2 things are done to the WADs:
1. The slots are remapped to their TombEngine equivalent
2. The holsters in the LARA_HOLSTERS and LARA_HOLSTERS_xxxx slots, originally mapped to 2 extra meshes in classic engines (4 and 8, resulting in 17 total meshes) are moved to the position that matches the other LARA_xxxx objects (1 and 4 - so the final mesh count is 15)

When using TombEditor's feature, it works as expected.
When using WadTool's feature, only step 1 seems to be done. Step 2 just seems to be skipped.

**Comment by Joey79100** [comment] 2023-05-20 17:04
@Lwmte Here's how to reproduce the issue.
_Now that you mention having similar results between TE and WT, I actually don't know TE's conversion function still works as expected, I haven't tried lately. Maybe it has the same issue as WT. But for sure, the WT one does have the issue right now._

1. Open a TR4 WAD/WAD2 file that has a "LARA_HOLSTERS" object.
2. Select "LARA_HOLSTERS", and hit "Edit Skeleton": you should see 17 meshes (from 0 to 16). Close the skeleton editor.
3. In the menu bar, select "Tools" > "Convert Wad to TombEngine...". It asks you a destination path, type a new WAD name and save.
4. Select "LARA_HOLSTERS", and hit "Edit Skeleton": you should see 15 meshes now (from 0 to 14). But you still see the 17 meshes from earlier.

Here is a test WAD you can use as an example (it is in .wad format, but it doesn't matter) :
[HorusGoddess_LegendWinterCustomEvergreen.zip](https://github.com/MontyTRC89/Tomb-Editor/files/11522812/HorusGoddess_LegendWinterCustomEvergreen.zip)

Here is a properly converted WAD for comparison. It was produced by Tomb Editor's "Convert level to TombEngine..." function _a while ago_.
[Winter-Green (fixed).zip](https://github.com/MontyTRC89/Tomb-Editor/files/11522809/Winter-Green.fixed.zip)

**Comment by Lwmte** [comment] 2023-05-22 18:57
I can't reproduce this issue. Here is a video recording of your repro steps producing correct result:


https://github.com/MontyTRC89/Tomb-Editor/assets/3331699/c4cd8182-8030-4e63-acaf-c0817a567e48

**Comment by Kubsy** [comment] 2023-05-24 21:39
I think Lewmte fixed here: https://github.com/MontyTRC89/Tomb-Editor/commit/c90176e545b56be40e1e0de14a192d396c5262d0 so im gonna close this

**Closed by Kubsy** 2023-05-24 21:39 UTC
Labels: bug, TombEngine

**Comment by Joey79100** [comment] 2023-05-29 14:06
Just tested. Can confirm it is working now, thanks!
